language: ruby

sudo: false

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - jruby-9.1.15.0
  - jruby-head

before_install: gem install bundler

script: bundle exec rake spec

cache: bundler
