title: Fend
description: Ruby data validation toolkit.
baseurl: /fend
url: aradunovic.github.io
markdown: kramdown
destination: build
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  -
    scope:
      type: pages
    values:
      layout: default
